language: php

php:
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction
  - php bin/console doctrine:database:create 
  - php bin/console doctrine:schema:create 
  - php bin/console doctrine:fixtures:load -n 

script:
  - phpunit

notifications:
  email: flase
