# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

    cebe\markdown\GithubMarkdown: ~

    AppBundle\Twig\TwigExtension:
        arguments: ['@cebe\markdown\GithubMarkdown']
        tags: ['twig.extension']

    app.counter_subscriber:
        class: AppBundle\EventListener\CounterSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }