# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.excerpt_extension:
        class: AppBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }

    app.counter_subscriber:
        class: AppBundle\EventListener\CounterSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    cebe\markdown\GithubMarkdown: ~