# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
      autowire: true
      autoconfigure: true
      public: false
      
  app.markdownTwigExtension:
    class: AppBundle\Twig\TwigExtension
    arguments:
      $markdown_parser: '@cebe.githubMarkdown'
    public: true
    tags:
      - { name: twig.extension }
  
  cebe.githubMarkdown:
    class: cebe\markdown\GithubMarkdown
    public: true
  
#  app.excerpt_extension:
#    class: AppBundle\Twig\TwigExtension
#    public: false
#    autowire: true
#    tags:
#      - { name: twig.extension }
  app.counter_subscriber:
    class: AppBundle\EventListener\CounterSubscriber
    tags:
      - { name: doctrine.event_subscriber, connection: default }
